
export const HomeData = [
    
    {
        id:1,
        title:"abella danger",
        to: '/abellaDanger',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/abellaDanger—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:2,
        title:"alexa grace",
        to: '/alexaGrace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alexaGrace—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:3,
        title:"ariana Marie",
        to: '/arianaMarie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/arianaMarie—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:4,
        title:"august Ames",
        to: '/augustAmes',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/augustAmes—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:5,
        title:"avery cristy",
        to: '/averyCristy',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/averyCristy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:6,
        title:"bella rolland",
        to: '/bellaRolland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bellaRolland—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    // {
    //     id:7,
    //     title:"blake eden",
    //     to: '/blakeEden',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeEden—index.jpg",
    //     color: 'hotpink',
        // txtcolor: 'white',
    // },
    // {
    //     id:7,
    //     title:"bunny colby",
    //     to: '/bunnyColby',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bunnyColby—index.jpg",
    //     color: 'hotpink',
        // txtcolor: 'white',
    // },
    {
        id:8,
        title:"casey calvert",
        to: '/caseyCalvert',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/caseyCalvert—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:9,
        title:"charlie red",
        to: '/charlieRed',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/charlieRed—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:10,
        title:"christy white",
        to: '/christyWhite',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/christyWhite—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    // {
    //     id:11,
    //     title:"danni rivers",
    //     to: '/danniRivers',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/danniRivers—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:12,
        title:"emily willis",
        to: '/emilyWillis',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emilyWillis—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:13,
        title:"eva elfie",
        to: '/evaElfie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evaElfie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:14,
        title:"evelyn claire",
        to: '/evelynClaire',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evelynClaire—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:15,
        title:"elsa jean",
        to: '/elsaJean',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elsaJean—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    // {
    //     id:16,
    //     title:"freya mayer",
    //     to: '/freyaMayer',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaMayer—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:17,
        title:"gianna dior",
        to: '/giannaDior',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/giannaDior—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:18,
        title:"gloria sol",
        to: '/gloriaSol',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/gloriaSol—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:19,
        title:"haley reed",
        to: '/haleyReed',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/haleyReed—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:20,
        title:"hazel moore",
        to: '/hazelMoore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/hazelMoore—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:21,
        title:"ivy aura",
        to: '/ivyAura',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ivyAura—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    // {
    //     id:22,
    //     title:"izzy lush",
    //     to: '/izzyLush',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/izzyLush—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:23,
        title:"janice griffith",
        to: '/janiceGriffith',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janiceGriffith―index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:24,
        title:"jaye summers",
        to: '/jayeSummers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jayeSummers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:25,
        title:"jessie saint",
        to: '/jessieSaint',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jessieSaint—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:26,
        title:"jia lissa",
        to: '/jiaLissa',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jiaLissa—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:27,
        title:"jillian janson",
        to: '/jillianJanson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillianJanson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:28,
        title:"jillKassidy",
        to: '/jordanJackson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillKassidy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:29,
        title:"kendra sunderland",
        to: '/kendraSunderland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kendraSunderland—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:30,
        title:"kenna james",
        to: '/kennaJames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kennaJames—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:31,
        title:"kristen scott",
        to: '/kristenScott',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kristenScott—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:32,
        title:"kyler quinn",
        to: '/kylerQquinn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kylerQuinn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:33,
        title:"lana rhoades",
        to: '/lanaRhoades',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lanaRhoades—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:34,
        title:"leah gotti",
        to: '/leahGotti',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leahGotti—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:35,
        title:"lena anderson",
        to: '/lenaAnderson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaAnderson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:36,
        title:"lena reif",
        to: '/lenaReif',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaReif—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:37,
        title:"little caprice",
        to: '/littleCaprice',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/littleCaprice—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:38,
        title:"liya silver",
        to: '/liyaSilver',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/liyaSilver—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:39,
        title:"maddy may",
        to: '/maddyMay',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/maddyMay—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:40,
        title:"melena maria rya",
        to: '/melenaMariaRya',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melenaMariaRya—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    // {
    //     id:41,
    //     title:"melody marksy",
    //     to: '/melodyMarksy',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melodyMarksy—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:42,
        title:"mila azul",
        to: '/milaAzul',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/milaAzul—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:43,
        title:"molly little",
        to: '/mollyLittle',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/mollyLittle—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:44,
        title:"nancy ace",
        to: '/nancyAce',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/nancyAce—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:45,
        title:"naomi swann",
        to: '/naomiSwann',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/naomiSwann—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    // {
    //     id:46,
    //     title:"ria sunn",
    //     to: '/riaSunn',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/riaSunn—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:47,
        title:"rika fane",
        to: '/rikaFane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rikaFane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:48,
        title:"riley reid",
        to: '/rileyReid',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rileyReid—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:49,
        title:"scarlit scandal",
        to: '/scarlitScandal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/scarlitScandal—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id:50,
        title:"stacy cruz",
        to: '/stacyCruz',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/stacyCruz—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    // {
    //     id:51,
    //     title:"sybil",
    //     to: '/sybil',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sybil—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },
    {
        id:52,
        title:"tiffany tatum",
        to: '/tiffanyTatum',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/tiffanyTatum—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id:53,
        title:"tori black",
        to: '/toriBlack',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/toriBlack—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    // {
    //     id:54,
    //     title:"uma jolie",
    //     to: '/umaJolie',
    //     image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/umaJolie—index.jpg",
    //     color: 'hotpink',
    //     txtcolor: 'white',
    // },

]