
import { v4 as uuidv4 } from 'uuid';
export const HomeData = [
    
    {
        id: uuidv4(),
        title:"abella danger",
        aliases: ['Bella Danger', 'Bella Manriquez', 'Bella Mevzinsky', 'Isabella Danger'],
        to: '/abellaDanger',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/abellaDanger—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"alecia fox",
        aliases: ['Arya', 'Alicia Fox', 'Rita Mochalkina', 'Alecia', 'Lissa, Aljona'],
        to: '/alecia-fox',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/aleciaFox—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"alexa grace",
        aliases: ['Alexa of Nyce', 'Meghan Marie', 'Renee Marie'],
        to: '/alexaGrace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alexaGrace—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"alicia williams",
        aliases: ['Alicia Willia', 'Victoria'],
        to: '/alecia-williams',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/aliciaWilliams—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ariana Marie",
        // aliases: ['Ariana Marie', 'Ariana'],
        to: '/ariana-marie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/arianaMarie—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"armani black",
        // aliases: ['Armani Black', 'Armani'],
        to: '/armani-black',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/armaniBlack—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"august Ames",
        aliases: ['Mercedes Grabowski',],
        to: '/august-ames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/augustAmes—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"avery cristy",
        aliases: ['Avery Christy'],
        to: '/avery-cristy',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/averyCristy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"bella rolland",
        aliases: ['Bella Roland'],
        to: '/bella-rolland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bellaRolland—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"blake blossom",
        // aliases: ['Blake', 'Blake Blossom'],
        to: '/blake-blossom',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeBlossom—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"blake eden",
        aliases: ['Blake', 'Blake Bartelli'],
        to: '/blake-cden',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeEden—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"bunny colby",
        aliases: ['Nadya Nabakova', 'ANNA'],
        to: '/bunny-colby',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bunnyColby—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"casey calvert",
        aliases: ['Sister Casey'],
        to: '/casey-calvert',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/caseyCalvert—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"charlie red",
        aliases: ['Charlie', 'Hexchen', 'Kris', 'Mimi', 'Tereza'],
        to: '/charlie-red',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/charlieRed—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"christy white",
        aliases: ['Christina Andreadou', 'Christine White', 'Xristina Andreadou'],
        to: '/christyWhite',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/christyWhite—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"danni rivers",
        aliases: ['Dani Rivers'],
        to: '/danniRivers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/danniRivers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"dominika c",
        aliases: ['Dita', 'Domika C', 'Dominica C', 'Dominika', 'Dominika A', 'Dominika Chybova', 'Dominika85', 'Dominique'],
        to: '/dominika-c',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/dominikaC—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"elena koshka",
        // aliases: ['Elena', 'Elena Koshka'],
        to: '/elena-koshka',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elenaKoshka—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"emelie crystal",
        aliases: ['Emelie Devot', 'Emilie Crystal'],
        to: '/emelie-crystal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emelieCrystal—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"emily willis",
        aliases: ['Litzy Lara Bañuelos'],
        to: '/emilyWillis',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emilyWillis—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"eva elfie",
        aliases: ['Brigitte', 'Lady Jay', 'Tieny Mieny', 'Tiny Teen'],
        to: '/evaElfie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evaElfie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"evelyn claire",
        aliases: ['Evelyn', 'Evelyn Claire'],
        to: '/evelynClaire',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evelynClaire—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"elsa jean",
        aliases: ['Elsa Dream', 'Elsa Dream Jean', 'Molly', 'Sapphire Howell'],
        to: '/elsaJean',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elsaJean—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"freya mayer",
        // aliases: ['Freya', 'Freya Mayer'],
        to: '/freyaMayer',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaMayer—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"freya parker",
        // aliases: ['Freya', 'Freya Parker'],
        to: '/freya-parker',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaParker—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"georgia jones",
        aliases: ['Alison Michelle Thompson', 'Alison Thompson', 'Georgia Rose', 'Georgie Jones', 'Larysa'],
        to: '/georgia-jones',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/georgiaJones—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"gianna dior",
        aliases: ['Emily Katherine Correro'],
        to: '/giannaDior',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/giannaDior—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"gloria sol",
        aliases: ['Aaliyah', 'Cameron', 'Carolina Quito', 'Dolores', 'Gloria', 'Penelope Y', 'Sofia', 'SofieQ', 'Sophia'],
        to: '/gloriaSol',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/gloriaSol—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"haley reed",
        aliases: ['Amy May', 'Jamie Rott'],
        to: '/haleyReed',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/haleyReed—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"hazel moore",
        aliases: ['Ellie'],
        to: '/hazelMoore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/hazelMoore—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ivy aura",
        to: '/ivyAura',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ivyAura—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"izzy lush",
        to: '/izzyLush',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/izzyLush—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jane wilde",
        to: '/jane-wilde',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janeWilde—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"janice griffith",
        to: '/janiceGriffith',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janiceGriffith―index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jaye summers",
        to: '/jayeSummers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jayeSummers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jessie saint",
        to: '/jessieSaint',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jessieSaint—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jia lissa",
        to: '/jiaLissa',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jiaLissa—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jillian janson",
        to: '/jillianJanson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillianJanson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jill kassidy",
        to: '/jordanJackson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillKassidy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"katrina colt",
        to: '/katrina-colt',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/katrinaColt—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"kendra sunderland",
        to: '/kendraSunderland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kendraSunderland—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kenna james",
        to: '/kennaJames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kennaJames—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kristen scott",
        to: '/kristenScott',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kristenScott—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kyler quinn",
        to: '/kylerQquinn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kylerQuinn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lana rhoades",
        to: '/lanaRhoades',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lanaRhoades—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"laney grey",
        to: '/laney-grey',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/laneyGrey—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"leah gotti",
        to: '/leah-gotti',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leahGotti—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"leanne lace",
        to: '/leanne-lace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leanneLace—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lena anderson",
        to: '/lenaAnderson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaAnderson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lena reif",
        to: '/lenaReif',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaReif—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lilly bell",
        to: '/lilly-bell',
    image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lillyBell—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lily larimar",
        // aliases: ["lily larimar"],
        to: '/lily-larimar',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lilyLarimar—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"little caprice",
        to: '/littleCaprice',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/littleCaprice—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"liya silver",
        to: '/liyaSilver',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/liyaSilver—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lottie magne",
        to: '/lottie-magne',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lottieMagne—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"maddy may",
        to: '/maddyMay',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/maddyMay—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"melena maria rya",
        to: '/melenaMariaRya',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melenaMariaRya—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"melody marks",
        to: '/melody-marks',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melodyMarks—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"mila azul",
        to: '/milaAzul',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/milaAzul—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"molly little",
        to: '/mollyLittle',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/mollyLittle—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"nancy ace",
        to: '/nancyAce',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/nancyAce—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"naomi swann",
        to: '/naomiSwann',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/naomiSwann—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"oxana chic",
        to: '/oxana-chic',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/oxanaChic—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"ria sunn",
        to: '/riaSunn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/riaSunn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"rika fane",
        to: '/rikaFane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rikaFane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"riley reid",
        to: '/rileyReid',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rileyReid—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"scarlit scandal",
        to: '/scarlitScandal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/scarlitScandal—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"sophia leone",
        to: '/sophia-leone',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sophiaLeone—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"stacy cruz",
        to: '/stacyCruz',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/stacyCruz—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"sybil",
        to: '/sybil',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sybil—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tiffany tatum",
        to: '/tiffanyTatum',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/tiffanyTatum—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tori black",
        to: '/toriBlack',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/toriBlack—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"uma jolie",
        to: '/umaJolie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/umaJolie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },

]