
import { v4 as uuidv4 } from 'uuid';
export const HomeData = [
    
    {
        id: uuidv4(),
        title:"abella danger",
        to: '/abellaDanger',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/abellaDanger—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    
    {
        id: uuidv4(),
        title:"alexa grace",
        to: '/alexaGrace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alexaGrace—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ariana Marie",
        to: '/ariana-marie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/arianaMarie—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"armani black",
        to: '/armani-black',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/armaniBlack—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"august Ames",
        to: '/august-ames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/augustAmes—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"avery cristy",
        to: '/avery-cristy',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/averyCristy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"bella rolland",
        to: '/bella-rolland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bellaRolland—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"blake eden",
        to: '/blake-cden',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeEden—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"bunny colby",
        to: '/bunny-colby',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bunnyColby—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"casey calvert",
        to: '/casey-calvert',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/caseyCalvert—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"charlie red",
        to: '/charlie-red',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/charlieRed—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"christy white",
        to: '/christyWhite',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/christyWhite—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"danni rivers",
        to: '/danniRivers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/danniRivers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"emily willis",
        to: '/emilyWillis',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emilyWillis—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"eva elfie",
        to: '/evaElfie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evaElfie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"evelyn claire",
        to: '/evelynClaire',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evelynClaire—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"elsa jean",
        to: '/elsaJean',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elsaJean—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"freya mayer",
        to: '/freyaMayer',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaMayer—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"gianna dior",
        to: '/giannaDior',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/giannaDior—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"gloria sol",
        to: '/gloriaSol',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/gloriaSol—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"haley reed",
        to: '/haleyReed',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/haleyReed—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"hazel moore",
        to: '/hazelMoore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/hazelMoore—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ivy aura",
        to: '/ivyAura',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ivyAura—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"izzy lush",
        to: '/izzyLush',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/izzyLush—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"janice griffith",
        to: '/janiceGriffith',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janiceGriffith―index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jaye summers",
        to: '/jayeSummers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jayeSummers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jessie saint",
        to: '/jessieSaint',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jessieSaint—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jia lissa",
        to: '/jiaLissa',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jiaLissa—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jillian janson",
        to: '/jillianJanson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillianJanson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jillKassidy",
        to: '/jordanJackson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillKassidy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"kendra sunderland",
        to: '/kendraSunderland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kendraSunderland—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kenna james",
        to: '/kennaJames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kennaJames—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kristen scott",
        to: '/kristenScott',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kristenScott—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kyler quinn",
        to: '/kylerQquinn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kylerQuinn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lana rhoades",
        to: '/lanaRhoades',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lanaRhoades—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"leah gotti",
        to: '/leah-gotti',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leahGotti—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lena anderson",
        to: '/lenaAnderson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaAnderson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lena reif",
        to: '/lenaReif',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaReif—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"little caprice",
        to: '/littleCaprice',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/littleCaprice—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"liya silver",
        to: '/liyaSilver',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/liyaSilver—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"maddy may",
        to: '/maddyMay',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/maddyMay—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"madi collins",
        to: '/madi-collins',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/madiCollins—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"melena maria rya",
        to: '/melenaMariaRya',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melenaMariaRya—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"melody marksy",
        to: '/melodyMarksy',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melodyMarksy—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"mila azul",
        to: '/milaAzul',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/milaAzul—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"molly little",
        to: '/mollyLittle',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/mollyLittle—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"nancy ace",
        to: '/nancyAce',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/nancyAce—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"naomi swann",
        to: '/naomiSwann',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/naomiSwann—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ria sunn",
        to: '/riaSunn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/riaSunn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"rika fane",
        to: '/rikaFane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rikaFane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"riley reid",
        to: '/rileyReid',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rileyReid—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"scarlit scandal",
        to: '/scarlitScandal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/scarlitScandal—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"sophia leone",
        to: '/sophia-leone',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sophiaLeone—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"stacy cruz",
        to: '/stacyCruz',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/stacyCruz—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"sydney cole",
        to: '/sydney-cole',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sydneyCole.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"sybil",
        to: '/sybil',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sybil—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tiffany tatum",
        to: '/tiffanyTatum',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/tiffanyTatum—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tori black",
        to: '/toriBlack',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/toriBlack—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"uma jolie",
        to: '/umaJolie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/umaJolie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },

]
